name: cloudmetrics (pip install)
on: [push, pull_request]

jobs:
  test:
    name: Test pip install python ${{ matrix.python-version }} on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Install package with pip
        run: |
          pip install .
      - name: Install packages with pip
        run: |
          python -m pip install ".[test]"
      - name: which python
        run: |
          which python
      - name: git info
        run: |
          git log --name-only -1 | cat -
#     - name: Setup tmate session
#       uses: mxschmitt/action-tmate@v3
      - name: Test with pytest
        run: |
          python -m pytest
      - name: Test notebooks with pytest
        run: |
          python -m pytest --nbval-lax
